from data.data import Datos
import custom_exceptions

class DatosPuntoDeposito(Datos):
    pass