from data.data import Datos
import custom_exceptions

class DatosPuntoRetiro(Datos):
    pass