from data.data import Datos
import custom_exceptions

class DatosDemanda(Datos):
    pass