from data.data import Datos
import custom_exceptions

class DatosReportes(Datos):
    pass