from data.data import Datos
import custom_exceptions

class DatosInsumo(Datos):
    pass